attempt to use get instead of try except
For the specialities check, it throws an error when using either method of accessing the dictionary (get or not) if the speciality is not found in the value.

2025-09-09 20:25:24 [scrapy.core.scraper] ERROR: Spider error processing <GET https://clinics.allerganbeauty.jp/api/all_point> (referer: None)
Traceback (most recent call last):
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\utils\defer.py", line 327, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\utils\python.py", line 368, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\utils\python.py", line 368, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "D:\Documents\alltheplaces\locations\middlewares\track_sources.py", line 31, in process_spider_output
    for item in result or []:
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\spidermiddlewares\referer.py", line 379, in <genexpr>
    return (self._set_referer(r, response) for r in result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 57, in <genexpr>
    return (r for r in result if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\spidermiddlewares\depth.py", line 54, in <genexpr>
    return (r for r in result if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\alltheplaces\.venv\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "D:\Documents\alltheplaces\locations\spiders\allerganbeauty_jp.py", line 50, in parse
    if jaspec in store.get("診療科目"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable